# resnet+delta_force_mod_single_veiw_force_encode.yaml
defaults:
  - _self_

name:  clock_clean_resnet_delta_no_force_single_view

model_config:
  continue_training: False
  start_epoch: 0
  end_epoch: 3000
  encoder: "resnet"
  action_def: "delta"
  force_mod: False
  single_view: True
  force_encode: False
  cross_attn: False