# resnet+delta_force_mod_single_veiw_force_encode.yaml
defaults:
  - _self_

name:  resnet_delta_no_force_single_view_force_no_encode

model_config:
  continue_training: False
  start_epoch: 0
  end_epoch: 3000
  encoder: "resnet"
  action_def: "delta"
  force_mod: True
  single_view: True
  force_encode: False
  force_encoder: "Linear"
  cross_attn: False
  hybrid: False
  duplicate_view: False
  crop: 1000 # 128