# resnet+delta_force_mod_single_veiw_force_encode.yaml
defaults:
  - _self_

name:  resnet_delta_force_mode_dual_view_cross_attn

model_config:
  continue_training: False
  start_epoch: 0
  end_epoch: 3000
  encoder: "resnet"
  action_def: "delta"
  force_mod: True
  single_view: False
  force_encode: False
  force_encoder: "CNN"
  cross_attn: True